### ISSUE TITLE
希望将题目和选项分开

### ISSUE THREAD

**Issue by violenttunder** [Azure99/MillionHero#2]
先感谢大神的项目！已捐赠
希望能够将题目和选项分开识别，过长的题目有换行的情况下，识别完会有部分自动填入选项a中，希望将题目和选项分开识别。

**Comment by Azure99** [comment]
事实上，就算分开了，这种情况也会存在，甚至会更严重。
目前对于OCR返回结果的处理是这样的，先把words_result按行合并，然后去掉空行，将倒数前3行作为ABC，剩下的作为题目。如果按照你说的，那么题干边长，答案的位置也会变化，是没有任何意义的

**Comment by JJJacky** [comment]
截图会有偏差，可以根据像素颜色进行切割，相当于将题目区抠出来   不会产生任何其他影响   因为我实际应用时会将弹幕截进去  使用可行性不太乐观

**Comment by Azure99** [comment]
但是兼容性呢，不同app界面是不一样的
