### ISSUE TITLE
搜索答案时。可以不需要带上问题，直接搜索答案。还有浏览器不需要指定用ie。ie真的很烂

### ISSUE THREAD

**Issue by mrhuangbh** [Azure99/MillionHero#9]

**Comment by Azure99** [comment]
大部分情况下直接搜索答案效果并不理想。

webbrowser默认是IE7，如果想要使用其他内核，非常麻烦，
如果直接打开其他浏览器，
1.无法实现高亮，
2.可能被360等软件拦截
